# fly.toml app configuration file generated for cuidgen on 2023-12-14T18:51:42+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "cuidgen"
primary_region = "nrt"

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/go"]

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
